### ISSUE TITLE
Strange double underline which dissapears after scroll

### ISSUE THREAD

**Issue by rofrol** [aeosynth/bk#15] opened 2021-01-04 03:49 UTC
![image](https://user-images.githubusercontent.com/28787/103499397-304e9400-4e48-11eb-87e1-ca5aa75b61f6.png)

And here after scroll:

![image](https://user-images.githubusercontent.com/28787/103499409-3fcddd00-4e48-11eb-8279-17dba27d7ad3.png)

**Comment by aeosynth** [comment] 2021-01-04 06:00
dupe of #9 . which terminal does this happen in?

**Closed by aeosynth** 2021-01-04 06:00 UTC

**Comment by rofrol** [comment] 2021-01-04 16:20
gnome-terminal Ubuntu 20.10
